name: background
description: "A Flutter package to display images or videos as backgrounds."
version: 1.3.0
homepage: https://farhansadikgalib.com
repository: https://github.com/farhansadikgalib/background
issue_tracker: https://github.com/farhansadikgalib/background/issues
maintainer: Farhan Sadik Galib
publisher: farhansadikgalib.com
screenshots:
  - description: 'Background with video.'
    path: screenshots/video.gif
  - description: 'Background with image.'
    path: screenshots/image.png

topics:
    - flutter
    - background
    - image
    - video
    - widget

environment:
  sdk: ^3.2.6
  flutter: ">=1.17.0"

dependencies:
  video_player:

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
flutter:


