name: background
description: "A Flutter package to display images or videos as backgrounds."
version: 1.1.0
homepage: https://github.com/farhansadikgalib/background
repository: https://github.com/farhansadikgalib/background
issue_tracker: https://github.com/farhansadikgalib/background/issues
maintainer: Farhan Sadik Galib
screenshots:
  - description: 'Background with image.'
    path: screenshots/image.png
  - description: 'Background with video.'
    path: screenshots/video.gif
environment:
  sdk: ^3.2.6
  flutter: ">=1.17.0"

dependencies:
  video_player:

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
flutter:
