name: background
description: "A Flutter package to display images or videos as backgrounds."
version: 0.0.1
homepage: https://github.com/farhansadikgalib/background
repository: https://github.com/farhansadikgalib/background
issue_tracker: https://github.com/farhansadikgalib/background/issues
maintainer: Farhan Sadik Galib
#screenshots:
#  - description: 'Content preview as blurred buffer.'
#    path: screenshots/blurred.png
#  - description: 'Content loaded.'
#    path: screenshots/loaded.png
environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  video_player:

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
flutter:
